services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile

  console:
    image: console
    build:
      context: .
      dockerfile: console/Dockerfile
